### ISSUE TITLE
Error deploying in local

### ISSUE THREAD

**Issue by onmax** [alastria/temp-alastriaID-truffle-contracts#38]
#### How to reproduce it? _Can also see [this gist](https://gist.github.com/onmax/39934d46b5ec49e33ff7521006e794f9)_
- Branch `develop`, with [last commit](https://github.com/alastria/alastriaID-truffle-contracts/commit/79cf65d4caa3aed65fc3c273019b4383bff1f877)
- Using `node v14.16.0`
- Installing dependencies using `npm install`
- (*) Using a local geth server:
```bash
geth --miner.gasprice 0 --http --http.corsdomain="https://remix.ethereum.org" --http.api web3,eth,debug,personal,net --vmdebug --datadir /tmp/geth --dev console
```
- Run in another terminal: `npm run migrateLocal`
_* This problem has also been tested with ganache in a docker_
#### Error
Running the last command will return the following error (geth on the left and deploy on the right):
![photo_2021-07-19_18-22-28](https://user-images.githubusercontent.com/22072217/129768287-3889eb18-5c9c-4194-8566-3552e5489edf.jpg)

#### Workaround
Before, publishing this issue, I've talked with @VictorNS69 which gave me a patch to solve this issue:
- Update dependencies
- Update migrations scripts (5 and 6 have been not fixed)

You can see those changes in this [PR](https://github.com/onmax/alastriaID-truffle-contracts/pull/1) in my own repository

Probably, there is a better way of addressing this issue but we don't know how

**Comment by VictorNS69** [comment]
The problem (_I think_) is that when I try to add these flags `{ gas: 0x6691b7, gasPrice: 0x0 }` to the [`truffle-config.js`](https://github.com/alastria/alastriaID-truffle-contracts/blob/develop/truffle-config.js#L50) file, they do not seem to load and are not set.

Does anyone know if I am doing something wrong, or maybe it is a truffle bug?

We also updated truffle dependencies:
```json
    "@truffle/config": "1.3.1",
    "@truffle/hdwallet-provider": "1.4.2",
    "keythereum": "1.2.0",
    "remixd": "0.2.4-alpha.0",
    "truffle": "5.4.2"
```

Thank you in advance!
