### ISSUE TITLE
Create a "How To" section in the documentation

### ISSUE THREAD

**Issue by VictorNS69** [alastria/temp-alastriaID-truffle-contracts#45]
We should add a new section called "How To" to explain the deployment and the upgrade process of the Smart Contracts.

Some important aspects in this documentation are:
- Enumerate the steps involving the upgradeability
- Detailed explanation about "what are we doing  this"

Also, it would be a good idea to explain the proxy pattern we are using (openzeppeling) and how we  are using it in Alastria.

**Comment by alejandroalffer** [comment]
Minor update in README.md to explain upgradeability function in https://github.com/alastria/alastriaID-truffle-contracts/tree/howto-update

Do not close this issue without running the commands and get captures from each step, and explain Proxy Pattern

**Comment by alejandroalffer** [comment]
The only comment we should make is that the change in line `47` in `hardhat.config.js` is to manually modify the EVM version for the deployment of SmartContracts in B or T.

**Comment by rober12** [comment]
Repository Miragtion to https://github.com/alastria/alastriaID-hardhat-contracts/tree/master
