### ISSUE TITLE
Create a new smart contract called AlastriaObjectRegistry.sol

### ISSUE THREAD

**Issue by rober12** [alastria/temp-alastriaID-truffle-contracts#62]
This smart contract will unify the AlastriaCredentialRegistry.sol and AlastriaPresentationRegistry.sol smart contracts.
It will store only the hash and the state of the objects without distinguishing which object is being talked about.

For this it is also necessary to unify the states of both smart contracts and change them from an enum to a numeric value. Later, in comments, we will mark the meaning of each state for credentials and presentations.

**Comment by juftavira** [comment]
The smartContract will hold the "object" hash and the status.
The status will be a numeric value, not an enum, this way the numeric value will be understood by the caller (in this case the library)
The numeric value will be re-used among credentials and presentation it would be nonsense to have values 0-9 for credentials and 10-19 for presentations as that would disclosure the kind of object.
Example:
Credentials have these possible statuses: {Valid, AskIssuer, Revoked, DeletedBySubject}
Valid would become 0, 
AskIssuer would become 1,
Revoked would become 2,
DeletedBySubject would become 3

Presentations have these possible statuses:  {Valid, Received, AskDeletion, DeletionConfirmation}
Valid would become 0,
Received would become 1,
AskDeletion would become 2,
DeletionConfirmation would become 3

Then the library will keep its functions for setting the status of Credentials and different functions for Presentations, then it will map those to the new function, sending the status as a numeric value.

**Comment by rober12** [comment]
Different aspects to be studied in depth, such as, the possibility that the status associated with credentials and presentations be included in the hash and not separately as up to now, although this makes it more difficult to consult the status of credentials and presentations.

**Comment by MisiakGeo** [comment]
Moving away from enums, could be better, when **Abigen** is used to compile the Alastria Smart Contracts, due to the fact that Abigen does not accept the enum data type at all. This action could possibly make, the development of Alastria based solutions, using Golang easier.

**Comment by rober12** [comment]
It is closed because a new task has been created with a more updated description according to eIDAS ARF.
