### ISSUE TITLE
Inherits the same function "_initialize" from two contracts

### ISSUE THREAD

**Issue by miguelGomezLZPF** [alastria/temp-alastriaID-truffle-contracts#7]
Fail to compile

```
/AlastriaIdentityManager.sol:14:1: TypeError: Derived contract must override function "_initialize". Two or more base classes define function with same name and parameter types.
```

**Comment by VictorNS69** [comment]
Any new with this issue? Will this issue be implemented or is it no longer necessary? @miguelGomezLZPF @nefera606 

We already deployed this Smart Contract in both local and t-network and they are working fine I think.

**Comment by VictorNS69** [comment]
This issue is already fixed in the actual code.
